### ISSUE TITLE
PRQ merge messages are duplicated

### ISSUE THREAD

**Issue by LordAro** [OpenTTD/DorpsGek-irc#7]
```
10:36:27 < DorpsGek_II> [OpenTTD/OpenTTD] sj26 merged pull request #6909: Add BACKSPACE as a mappable hotkey https://github.com/OpenTTD/OpenTTD/pull/6909
10:36:27 < DorpsGek_II> [OpenTTD/OpenTTD] michicc pushed 1 commits to master:
10:36:27 < DorpsGek_II>   - Add: BACKSPACE can be mapped as a hotkey (by sj26)
10:36:28 < DorpsGek_II> https://github.com/OpenTTD/OpenTTD/commit/1a73c3983863
```

Not sure how feasible this is, given the information received from GitHub, but these messages are largely redundant, and it'd be nice if they could be deduplicated (probably by removing the commit, rather than the merge?)

**Comment by glx22** [comment]
It's not really a duplicate, just two different sources. I think it's not possible for the bot to know they are related.

**Comment by LordAro** [comment]
Yeah, hence the "not sure how feasible this is" :)
GitHub webinterface links commits to pull requests, I figured there might be something in the JSON API that does the same thing

**Comment by LordAro** [comment]
Alternatively, since no one should be pushing directory to master anyway, perhaps those messages could be suppressed?

**Comment by TrueBrain** [comment]
Issue in https://github.com/OpenTTD/DorpsGek-github/issues/13

**Comment by TrueBrain** [comment]
I went for the: if a push follows a PR with the same sha, ignore the push.
